### ISSUE TITLE
Compilation problem with gcc 11

### ISSUE THREAD

**Issue by ycollet** [brummer10/gxtuner#19]
Hello,

I met an error message while compiling gxtuner on Fedora 34 with gcc 11:
```
./gxtuner.h:30:1: note: 'extern "C"' linkage started here
   30 | extern "C" {
      | ^~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/gatomic.h:31,
                 from /usr/include/glib-2.0/glib/gthread.h:32,
                 from /usr/include/glib-2.0/glib/gasyncqueue.h:32,
                 from /usr/include/glib-2.0/glib.h:32,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from ./gxtuner.h:33,
                 from gxtuner.cpp:24:
/usr/include/c++/11/type_traits:3215:3: error: template with C linkage
 3215 |   template<typename _Tp>
      |   ^~~~~~~~

```

**Comment by smcv** [comment]
I don't think this is caused by upgrading to gcc 11, I think it's caused by upgrading to GLib 2.68.

GLib and GTK both include extern "C" guards in their header files, so it is unnecessary to wrap them in an extern "C" block.

A redundant extern "C" block can be harmful, because header files might test `#ifdef __cplusplus` and include C++ syntax if it is defined, even in an otherwise C header. In particular, GLib has done this since version 2.68, in order to make macros like g_object_ref() type-safe when called from C++ code. the result was that this project failed to compile.

One way to fix this is to stop wrapping `extern "C" { ... }` blocks around the inclusion of third-party header files.

Another way to fix this is to ask GLib to behave like an older version, by defining the macros `GLIB_VERSION_MIN_REQUIRED` and `GLIB_VERSION_MAX_ALLOWED` to one of the constants provided by GLib versions since 2.26, for example `-DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_42 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_42` if GLib 2.42 is a suitable version to depend on. This will also disable deprecation warnings for things that were deprecated in newer GLib versions.

**Comment by rekado** [comment]
I applied #21 in my build and I can confirm that it fixes the compilation error.

**Comment by brummer10** [comment]
Sorry for the delay in response, it's just that I ain't use GxTuner any more. 
I moved on with a new tuner I've put here:
https://github.com/brummer10/XTuner
So, if anyone like to take over maintenance for GxTuner, it will be welcome.
